{ config, lib, pkgs, ... }: {

  environment.systemPackages = with pkgs; [
    wireguard-tools
  ];

  networking ={
    nat.enable = true;
    nat.externalInterface = "enp1s0";
    nat.internalInterfaces = [ "sra0" ];
    firewall = {
      allowedTCPPorts = [ 53 ];
      allowedUDPPorts = [ 51820 ];
    };
  };
  networking.wireguard.interfaces = {
    sra0 = {
      ips = [ "20.20.100.1/24"];
      listenPort = 51820;
      postSetup = ''
        ${pkgs.iptables}/bin/iptables -t nat -A POSTROUTING -s 20.20.100.0/16 -o enp1s0 -j MASQUERADE
      '';
      postShutdown = ''
        ${pkgs.iptables}/bin/iptables -t nat -D POSTROUTING -s 20.20.100.0/16 -o enp1s0 -j MASQUERADE
      '';
      privateKeyFile = "/home/auros/wireguard-keys/private";
      peers = [
        {
          publicKey = "BvzaDqQVNagCvsZptLouE5nKaCSWruIVKXSyj5MUwAc=";
          endpoint = "192.168.12.170:51820";
          allowedIPs = [ "20.20.100.2/32" ];
        }
        {
          publicKey = "pxuMqA0c3gruTK2yxa2bxbWLn62jAJXwetgrZqjD3Cw=";
          endpoint = "192.168.12.171:51820";
          allowedIPs = [ "20.20.100.3/32" ];
        }

      ];
    };
  };

  }

#important :: you have to check peers publicKey by 'sudo wg show' in peers machine
#even if the private key is same, but every public key generated by wg genkey has changed everytime!!
#
#https://nixos.wiki/wiki/WireGuard
#https://github.com/jjdosa/mysystem/blob/a8d661be2c7c9a739211f772de574a8e5138dd6d/nixosConfigurations/features/wireguard.nix
